language: r
dist: xenial
addons:
  snaps:
    - hugo
cache:
  packages: yes

env:
  global:
    - R_PKG="$(basename $TRAVIS_REPO_SLUG)" PATH=$HOME/bin:$PATH

repos:
  XRAN: https://xran.yihui.name

before_script:
  - "curl https://xran.yihui.name/.gitconfig -o ~/.gitconfig"
  - Rscript -e "update.packages(.libPaths()[1], ask = FALSE)"
  - Rscript -e 'xfun::pkg_load2(c("covr", "xml2"))'
  - R CMD INSTALL .
  - "Rscript -e \"Sys.which('hugo');blogdown::hugo_version()\""

after_success:
  - Rscript -e 'covr::codecov()'
  - "(curl https://xran.yihui.name/r-xran | bash)"
